# Generated by Django 4.1.7 on 2023-04-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_application2010e_part1_consent_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application2010e_part1",
            old_name="application_Id",
            new_name="application_ID",
        ),
    ]
