# Generated by Django 4.1.7 on 2023-04-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0002_profile_delete_teacher"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
